<a href="https://colab.research.google.com/github/Sunisa78-8/Python_dataviz2023/blob/main/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive # เชื่อมบัญชีกับ google drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import numpy as np
import pandas as pd
import os

In [4]:
#เข้าไป path ใน google drive
import os
os.chdir('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz')

!pwd #เช็ค path ที่กำลังทำงานอยู่

/content/drive/.shortcut-targets-by-id/1hJRbv1gQq_buBvNPn3Uy86oBasUU04FN/Final2023_DataViz

In [5]:
!ls

Final.pdf				 POS_transactions_20171207-20171219.csv
POS_operator_logs_20171207-20171219.csv  POS_transactions_20190213-20190226.csv
POS_operator_logs_20190213-20190226.csv  POS_transactions_20190328-20190410.csv
POS_operator_logs_20190328-20190410.csv

In [6]:
operator1 = pd.read_csv('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz/POS_operator_logs_20171207-20171219.csv')
operator2 = pd.read_csv('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz/POS_operator_logs_20190213-20190226.csv')
operator3  = pd.read_csv('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz/POS_operator_logs_20190328-20190410.csv')
tran1 = pd.read_csv('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz/POS_transactions_20171207-20171219.csv')
tran2 = pd.read_csv('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz/POS_transactions_20190213-20190226.csv')
tran3= pd.read_csv('/content/drive/MyDrive/Final_Dataviz/Final2023_DataViz/POS_transactions_20190328-20190410.csv')

In [7]:
operator1.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [8]:
operator2.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [9]:
operator3.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [10]:
tran1.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [11]:
tran2.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [12]:
tran3.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [13]:
operator = pd.concat([operator1,operator2,operator3],ignore_index=True)

In [14]:
transactions = pd.concat([tran1,tran2,tran3],ignore_index = True)

In [15]:
operator

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...
14099,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff
14100,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff
14101,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn
14102,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff
14103,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff

In [16]:
transactions

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
163264,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14
163265,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90
163266,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99
163267,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88
163268,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33

In [ ]:
pp = transactions.merge(operator,how='left' , left_on='WorkstationGroupID' , right_on = 'WorkstationGroupID')

In [ ]:
pp =pd.merge(transactions,operator,how = 'left' , on=['WorkstationGroupID'])